$(function(){
  var game = new Game();
  $('.choice').click(function(e){
    //get user input choice
    var choice = $(this).data().name;

    //get the current turn generated by computer
    var currentTurn = game.currentTurn;
    renderChoice(choice, currentTurn.computerChoice)
    //calculate the winner
    currentTurn.addPlayerChoice(choice);
    var winner = currentTurn.winner

    //prepare for new turn
    game.newTurn();

    //log current standings
    if (winner !== 'draw'){
      $('#'+winner+'-score').text(game[ winner + 'Count'])
    }
    $('#winner-log').text(winner + ' wins!');
  });
});

function renderChoice(playerChoice, computerChoice){
  const imageUrls = {
    rock: './img/rock.png',
    paper: './img/paper.png',
    scissors: './img/scissors.png',
  }

  //update the screen with the computer and player choices
  $('#player-choice').html('<img src="'+imageUrls[playerChoice]+'"/>');
  $('#computer-choice').html('<img src="'+imageUrls[computerChoice]+'"/>');
}
