$(function(){
  var game = new Game();
  $('.choice').click(function(e){
    //get user input choice
    var choice = $(this).data().name;

    //get the current turn generated by computer
    var currentTurn = game.currentTurn;

    //update the screen with the computer and player choices
    $('#player-choice').text(choice);
    $('#computer-choice').text(currentTurn.computerChoice);

    //calculate the winner
    currentTurn.addPlayerChoice(choice);
    var winner = currentTurn.winner

    //prepare for new turn
    game.newTurn();

    //log current standings
    if (winner !== 'draw'){
      $('#'+winner+'-score').text(game[ winner + 'Count'])
    }
  });
});


